/*
Enter your query here.

*/

SELECT CONCAT(NAME,CONCAT("(",CONCAT(SUBSTR(UPPER(OCCUPATION),1,1),")"))) FROM OCCUPATIONS ORDER BY NAME;
SELECT "There are total ",COUNT(*), CONCAT(LOWER(OCCUPATION),"s.")  FROM OCCUPATIONS GROUP BY OCCUPATION ORDER BY COUNT(*),OCCUPATION;


--Alternate Solution

SELECT concat(NAME, CASE WHEN occupation = "Doctor" THEN "(D)" WHEN occupation = "Professor" THEN "(P)" WHEN occupation = "Singer" THEN "(S)" WHEN occupation = "Actor" THEN "(A)" END ) 
FROM OCCUPATIONS ORDER BY NAME; SELECT "There are total", COUNT(OCCUPATION), concat(LOWER(OCCUPATION),"s") FROM OCCUPATIONS GROUP BY OCCUPATION ORDER BY COUNT(OCCUPATION) ASC, OCCUPATION ASC;

