MYSQL  

select DISTINCT CITY from STATION WHERE (ID MOD 2) = 0;

MS MYSQL   MYSQL  

select DISTINCT CITY from STATION WHERE (ID % 2) = 0;

ORACLE		MYSQL

SELECT DISTINCT CITY FROM STATION WHERE MOD(ID,2)=0;

