MS SQL

SELECT DISTINCT CITY FROM STATION WHERE CITY NOT LIKE '%[AEIOU]'

MYSQL

SELECT distinct city FROM station WHERE city REGEXP '[^aeiou]$';

SELECT DISTINCT CITY FROM STATION WHERE CITY NOT REGEXP '[aeiou]$';

ORACLE
SELECT DISTINCT(CITY) FROM STATION WHERE NOT REGEXP_LIKE (CITY, '[a,e,i,o,u]$', 'i');